[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 2 --log-level debug --timeout-keep-alive 75"
healthcheckPath = "/"
healthcheckTimeout = 180
restartPolicy = "always" 